import { Dimensions, StyleSheet } from "react-native";

const screenWidth = Dimensions.get("window").width;

const styles = StyleSheet.create({
  background: { flex: 1, resizeMode: "cover" },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  leftSection: { flexDirection: "row", alignItems: "center" },
  greeting: {
    fontSize: 18,
    fontWeight: "400",
    color: "#000",
    marginLeft: 10,
    fontFamily: "GelicaMedium",
    lineHeight: 22,
  },
  icon: { width: 28, height: 28, marginBottom: 6 },
  rightIcons: { flexDirection: "row", alignItems: "center" },
  iconButton: { marginLeft: 16 },
  card: {
    backgroundColor: "#fff",
    width: 64,
    height: 59,
    marginRight: 12,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  cardText: {
    marginTop: 4,
    fontSize: 12,
    fontWeight: "400",
    color: "#000",
    textAlign: "center",
    fontFamily: "GelicaRegular",
    lineHeight: 16,
  },
  optionCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    width: 350,
    height: 59,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginBottom: 10,
    alignSelf: "center",
  },
  optionIconWrapper: { marginRight: 12 },
  optionIcon: { width: 28, height: 28 },
  dailyContainer: { paddingHorizontal: 16, marginTop: 10 },
  sectionHeading: {
    fontSize: 18,
    fontFamily: "GelicaMedium",
    color: "#444",
    marginBottom: 12,
    paddingHorizontal: 4,
    lineHeight: 20,
  },
  optionTitle: {
    fontSize: 16,
    fontFamily: "GelicaMedium",
    color: "#000",
    marginBottom: 2,
    lineHeight: 20,
  },
  optionSubtitle: {
    fontSize: 13,
    fontFamily: "GelicaRegular",
    color: "#666",
    lineHeight: 18,
  },
  kalpXContainer: { paddingHorizontal: 16, marginTop: 20 },
  kalpXCard: {
    width: 150,
    height: 145,
    backgroundColor: "#fff",
    borderColor: "#ffd6a5",
    borderWidth: 0.5,
    borderRadius: 12,
    overflow: "hidden",
    marginBottom: 12,
    padding: 8,
  },
  kalpXImage: { width: "100%", height: 100, borderRadius: 8 },
  kalpXTitle: {
    fontSize: 12,
    fontFamily: "GelicaMedium",
    color: "#000",
    marginTop: 6,
    marginHorizontal: 8,
    textAlign: "left",
    lineHeight: 18,
  },
});

export default styles;