import { Dimensions, StyleSheet } from "react-native";

const screenWidth = Dimensions.get("window").width;

const styles = StyleSheet.create({
  // 👇 (keep your same styles as before)
  headerImage: { width: "100%", height: 260, justifyContent: "space-between" },
  imageStyle: { borderBottomLeftRadius: 20, borderBottomRightRadius: 20 },
  iconButton: {
    marginTop: 40,
    marginLeft: 16,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(0,0,0,0.5)",
    alignItems: "center",
    justifyContent: "center",
  },
  headerBottom: { padding: 16 },
  headerTitle: { fontSize: 28, fontWeight: "700", color: "#fff" },
  locationBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    marginTop: 8,
    alignSelf: "flex-start",
  },
  locationText: { marginLeft: 4, fontSize: 12, fontWeight: "700", color: "#333" },

  title: { fontSize: 29, fontWeight: "500",color:"#000000" ,marginBottom: 16 },
  label: {  marginTop:8,fontSize: 16, fontWeight: "500",color: "#000000" , marginBottom: 8 },
  selector: {
    borderWidth: 1,
    borderColor: "#FAD38C",
    borderRadius: 15,
    padding: 12,
    marginBottom: 16,
    backgroundColor: "#FFFFFF",
  },
  selectorText: { fontSize: 14, fontWeight: "400",color: "#000000" },
  input: {
    borderWidth: 1,
    borderColor: "#FAD38C",
    borderRadius: 15,
    padding: 10,
    marginBottom: 12,
  },
  textarea: { height: 100, textAlignVertical: "top" },
  checkboxRow: { flexDirection: "row", alignItems: "center", marginBottom: 12 },
  checkbox: {
    width: 20,
    height: 20,
    borderWidth: 1,
    borderColor: "#FAD38C",
    marginRight: 8,
    borderRadius: 4,
  },
  checkedBox: { backgroundColor: "#444" },
  checkboxText: { flex: 1,fontSize: 14, fontWeight: "400",color: "#000000" },
  row: { flexDirection: "row", marginBottom: 12 },
  option: {
    flex: 1,
    padding: 10,
    borderWidth: 1,
    borderColor: "#FFFFFF",
    backgroundColor:"#FFF7E8",
    borderRadius:20,
    marginRight: 8,
    alignItems: "center",
  },
  optionSelected: {    borderColor: "#FAD38C",},
  optionText: { color: "#000000" ,fontSize: 14, fontWeight: "400"},
  optionTextSelected: {  color: "#000000" ,fontSize: 14, fontWeight: "400"},

  footer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#fff",
    padding: 16,
    borderTopWidth: 1,
    borderColor: "#eee",
  },
  submitButton: {
    backgroundColor: "#9C6B2F",
    padding: 14,
    borderRadius: 8,
    alignItems: "center",
  },
  submitButtonText: { color: "#fff", fontWeight: "600", fontSize: 16 },

  modalOverlay: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  modalContent: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    maxHeight: "70%",
    paddingBottom: 20,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 16,
    borderBottomWidth: 1,
    borderColor: "#eee",
  },
  modalTitle: { fontSize: 18, fontWeight: "700" },
  radioRow: { flexDirection: "row", alignItems: "center", padding: 16 },
  radio: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 2,
    borderColor: "#999",
    marginRight: 12,
  },
  radioSelected: { backgroundColor: "#9C6B2F", borderColor: "#9C6B2F" },
  radioText: { fontSize: 16, color: "#333" },
    submitText: {
    color: "#fff",
    fontSize: 16,
    fontFamily: "GelicaMedium",
    lineHeight: 22,
  },
});

export default styles;