import { Dimensions, StyleSheet } from "react-native";

const screenWidth = Dimensions.get("window").width;

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#fffaf5" },
  scroll: { flex: 1 },
  headerImage: { height: 220, justifyContent: "flex-end" },
  imageStyle: {
    borderBottomLeftRadius: 25,
    borderBottomRightRadius: 25,
  },
  title: {marginHorizontal:16,marginTop:12 ,fontSize: 29, fontWeight: "500",color:"#000000" ,marginBottom: 16 },
  titlesubText:{fontSize: 16, fontWeight: "300",color:"#000000" ,marginBottom: 16 },
  iconButton: {
    backgroundColor: "rgba(0,0,0,0.3)",
    padding: 8,
    borderRadius: 20,
    position: "absolute",
    top: 36,
    left: 16,
  },
  headerBottom: {
    padding: 16,
    marginBottom: 12,
  },
  headerTitle: {
    fontSize: 22,
    fontFamily: "GelicaBold",
    color: "#fff",
    marginBottom: 6,
    // lineHeight: 28,
  },
  locationBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.9)",
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 4,
    alignSelf: "flex-start",
  },
  locationText: {
    fontSize: 13,
    color: "#444",
    marginLeft: 4,
      // lineHeight: 18,
    fontFamily: "GelicaRegular",
  },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  durationBox: {
    borderWidth: 1,
    borderColor: "#FAD38C",
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: "#fff",
  },
  durationRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
  },
  checkbox: {
    width: 18,
    height: 18,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "#aaa",
    marginRight: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
  },
  checkboxOn: { backgroundColor: "#b97f28", borderColor: "#b97f28" },
  durationText: {
    fontSize: 14,
      // lineHeight: 20,
    color: "#333",
    fontFamily: "GelicaRegular",
  },
  experienceRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginVertical: 10,
  },
  textArea: {
     borderColor: "#FAD38C",
    backgroundColor: "#fff",
    borderRadius: 12,
    minHeight: 120,
    padding: 12,
    textAlignVertical: "top",
    fontSize: 14,
    color: "#333",
    fontFamily: "GelicaRegular",
      // lineHeight: 20,
    borderWidth:1,
  },
  footer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#fffaf5",
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: "#eee",
  },
  submitButton: {
    backgroundColor: "#a67c52",
    padding: 14,
    borderRadius: 10,
    alignItems: "center",
  },
  submitText: {
    color: "#fff",
    fontSize: 16,
    fontFamily: "GelicaMedium",
      // lineHeight: 22,
  },
});

export default styles;
