import { Dimensions, StyleSheet } from "react-native";

const screenWidth = Dimensions.get("window").width;

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#fffaf5" },
  scroll: { flex: 1 },
  headerImage: { height: 220, justifyContent: "flex-end" },
  imageStyle: {
    borderBottomLeftRadius: 25,
    borderBottomRightRadius: 25,
  },
  iconButton: {
    backgroundColor: "rgba(0,0,0,0.5)",
    padding: 8,
    borderRadius: 20,
    position: "absolute",
    top: 46,
    left: 16,
  },
  headerBottom: {
    marginHorizontal: 16,
    marginVertical:6,
    // marginBottom: 12,
    flexDirection:"row",
    justifyContent:"space-between",
    alignItems:"center"
  },
  headerTitle: {
    fontSize: 20,
    fontFamily: "GelicaMedium",
    color: "#000000",
    // marginBottom: 6,
    lineHeight: 28,
  },
  planText:{
    fontSize: 16,
    fontFamily: "GelicaMedium",
    color: "#000000",
        // fontFamily: "GelicaMedium",
  },
  subText:{
    marginTop:4,
fontSize: 14,
    fontFamily: "GelicaMedium",
    color: "#A09CAB",
  },
  locationBadge: {
    flexDirection: "row",
    alignItems: "center",
    // backgroundColor: "rgba(255,255,255,0.9)",
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 4,
    alignSelf: "flex-start",
  },
  locationText: {
    fontSize: 14,
    color: "#000000",
    marginLeft: 4,
    lineHeight: 18,
    fontFamily: "GelicaRegular",
  },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  durationBox: {
    borderWidth: 1,
    borderColor: "#FAD38C",
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: "#fff",
  },
  durationRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
  },
  checkbox: {
    width: 18,
    height: 18,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "#aaa",
    marginRight: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
  },
  checkboxOn: { backgroundColor: "#b97f28", borderColor: "#b97f28" },
  durationText: {
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "400",
    color: "#333333",
    fontFamily: "GelicaRegular",
  },
  experienceRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginVertical: 10,
  },
  textArea: {
    borderWidth: 1,
    borderColor: "#FAD38C",
    backgroundColor: "#fff",
    borderRadius: 12,
    minHeight: 120,
    padding: 12,
    textAlignVertical: "top",
    fontSize: 14,
    color: "#333",
    fontFamily: "GelicaRegular",
    lineHeight: 20,
  },
  footer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#fffaf5",
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: "#eee",
  },
  submitButton: {
    backgroundColor: "#a67c52",
    padding: 14,
    borderRadius: 10,
    alignItems: "center",
  },
  submitText: {
    color: "#fff",
    fontSize: 16,
    fontFamily: "GelicaMedium",
    lineHeight: 22,
  },
});

export default styles;
