packages:
  - 'apps/*'
  - 'packages/*'
patchedDependencies:
  '@stripe/stripe-react-native@0.45.0': patches/@stripe__stripe-react-native@0.45.0.patch
  react-native@0.79.6: patches/react-native@0.79.6.patch
