import { Dimensions, StyleSheet } from "react-native";

const screenWidth = Dimensions.get("window").width;
const screenHeight = Dimensions.get("window").height;

const  styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#fefaf2", // matches card background
  },
  background: {
    flex: 1,
    resizeMode: "cover",
  },
  scrollContainer: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  brand: {
    fontSize: 38,
    textAlign: "center",
    fontWeight: "400",
    color: "#6c4b2f",
    marginBottom: 6,
    fontFamily: "GelicaBold",
    lineHeight: 40,
  },
  heading: {
    fontSize: 18,
    textAlign: "center",
    fontWeight: "400",
    marginBottom: 20,
    color: "#66605a",
    fontFamily: "GelicaRegular",
    lineHeight: 40,
  },
  googleButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#ffdeb6",
    marginBottom: 30,
    width: screenWidth * 0.85,
    justifyContent: "center",
  },
  googleIcon: {
    width: 20,
    height: 20,
    marginRight: 10,
  },
  googleText: {
    fontSize: 16,
    color: "#000",
    fontWeight: "500",
    fontFamily: "GelicaMedium",
    lineHeight: 20,
  },
  card: {
    width: screenWidth * 0.85,
    height:"55%",
    backgroundColor: "#fefaf2",
    borderRadius: 20,
    padding: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 5,
  },
  cardTitleLine1: {
    fontSize: 20,
    color: "#000",
    fontFamily: "GelicaLight",
    fontWeight: "500",
    lineHeight: 40,
  },
  cardTitleLine2: {
    fontSize: 32,
    marginBottom: 8,
    color: "#000",
    fontFamily: "GelicaLight",
    fontWeight: "300",
    lineHeight: 40,
  },
  subTitle: {
    fontSize: 14,
    marginVertical: 10,
    color: "#000000",
    fontFamily: "GelicaLight",
    fontWeight: "400",
    lineHeight: 18,
  },
  input: {
    borderWidth: 1,
    borderColor: "#9e9c98",
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
    backgroundColor: "#fefaf2",
    color: "#000",
    fontFamily: "GelicaRegular",
    fontSize: 14,
    lineHeight: 18,
  },
  button: {
    backgroundColor: "#ca8a04",
    paddingVertical: 14,
    borderRadius: 25,
    alignItems: "center",
    marginTop: 20,
  },
  buttonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
    fontFamily: "GelicaMedium",
    lineHeight: 20,
  },
  footerContainer: {
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 18,
  },
  footer: {
    fontSize: 14,
    fontFamily: "GelicaRegular",
    color: "#666360",
    lineHeight: 18,
  },
  login: {
    fontSize: 14,
    fontFamily: "GelicaRegular",
    color: "#666360",
    lineHeight: 18,
  },
  error: {
    fontSize: 12,
    color: "red",
    marginBottom: 5,
    fontFamily: "GelicaRegular",
    lineHeight: 16,
  },
  success: {
    fontSize: 12,
    color: "green",
    marginBottom: 10,
    fontFamily: "GelicaRegular",
    lineHeight: 16,
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginVertical: 8,
  },
  checkboxContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  checkbox: {
    width: 16,
    height: 16,
    borderWidth: 1,
    borderColor: "#000",
    marginRight: 4,
    justifyContent: "center",
    alignItems: "center",
  },
  checked: {
    backgroundColor: "#000",
  },
  checkmark: {
    color: "#fff",
    fontSize: 10,
  },
  checkboxLabel: {
    fontSize: 12,
    color: "#000",
    fontFamily: "GelicaRegular",
    lineHeight: 16,
  },
  forgot: {
    fontSize: 12,
    color: "black",
    fontFamily: "GelicaRegular",
    lineHeight: 16,
  },
});

export default styles;