// All registered block types — sourced from apps/mobile/src/engine/BlockRenderer.tsx blockMap.
// When adding a new block to BlockRenderer, add the type here too.

export const BLOCK_TYPES = {
  // Original blocks
  HEADLINE: 'headline',
  SUBTEXT: 'subtext',
  INSTRUCTION_TEXT: 'instruction_text',
  PRIMARY_BUTTON: 'primary_button',
  LOTUS_LOGO: 'lotus_logo',
  CHOICE_CARD: 'choice_card',
  CHOICE_GRID: 'choice_grid',
  BASELINE_SLIDER: 'baseline_slider',
  IMAGE: 'image',
  PRACTICE_CARD: 'practice_card',
  SANKALP_DISPLAY: 'sankalp_display',
  BREATH_ANIMATION: 'breath_animation',
  // Phase 3a
  REP_COUNTER: 'rep_counter',
  MANTRA_DISPLAY: 'mantra_display',
  TIMER_DISPLAY: 'timer_display',
  AUDIO_PLAYER: 'audio_player',
  CHIP_LIST: 'chip_list',
  DIAMOND_DIVIDER: 'diamond_divider',
  GROUNDING_LIST: 'grounding_list',
  TEXTAREA: 'textarea',
  CARD_LIST: 'card_list',
  COMPLETION_CARD: 'completion_card',
  PRACTICE_STEPS: 'practice_steps',
  PROGRESS_BAR: 'progress_bar',
  HOLD_TRIGGER: 'hold_trigger',
  FOOTER_BUTTONS: 'footer_buttons',
  ADDITIONAL_ITEMS_SECTION: 'additional_items_section',
  // Phase 3b
  SPACER: 'spacer',
  MICRO_LABEL: 'micro_label',
  HELPER_TEXT: 'helper_text',
  LINK_TEXT: 'link_text',
  LOTUS_HEADER: 'lotus_header',
  INSIGHT_BOX: 'insight_box',
  IDENTITY_INDICATOR: 'identity_indicator',
  IDENTITY_DELTA: 'identity_delta',
  SUMMARY_BLOCK: 'summary_block',
  FEEDBACK_RECAP: 'feedback_recap',
  REP_COUNTER_FEEDBACK: 'rep_counter_feedback',
  TEXT_INPUT: 'text_input',
  OPTION_PICKER: 'option_picker',
  PAUSE_ORB: 'pause_orb',
  TIMER_CONTROLS: 'timer_controls',
  TOAST_MESSAGE: 'toast_message',
  CYCLE_REFLECTION: 'cycle_reflection',
  CYCLE_REFLECTION_RESULTS: 'cycle_reflection_results',
  MANTRA_SELECTION_LIST: 'mantra_selection_list',
  TRIGGER_PATTERN: 'trigger_pattern',
  // Phase 4
  CHALLENGE_TEXT: 'challenge_text',
  FORM_FIELDS: 'form_fields',
  GRAPH: 'graph',
  GUIDE: 'guide',
  HOLD_BUTTON: 'hold_button',
  MANTRA: 'mantra',
  PRACTICE: 'practice',
  SANKALP: 'sankalp',
  PRESS_AND_HOLD: 'press_and_hold',
  PRESS_AND_HOLD_CIRCULAR: 'press_and_hold_circular',
  TIMELINE: 'timeline',
  TREND_CHART: 'trend_chart',
  VOICE_RECORDER: 'voice_recorder',
  PROGRESS_SECTION: 'progress_section',
  ACTIVITY_STATS: 'activity_stats',
  // Week 1 — Onboarding
  ONBOARDING_CONVERSATION_TURN: 'onboarding_conversation_turn',
  VOICE_TEXT_FORK: 'voice_text_fork',
  GUIDANCE_MODE_PICKER: 'guidance_mode_picker',
  FIRST_RECOGNITION: 'first_recognition',
  PATH_EMERGES: 'path_emerges',
  ONBOARDING_INTRO_HERO: 'onboarding_intro_hero',
  // Week 2 — Dashboard
  MORNING_BRIEFING: 'morning_briefing',
  FOCUS_PHRASE: 'focus_phrase',
  CORE_ITEMS_LIST: 'core_items_list',
  CHECK_IN_CARD_COMPACT: 'check_in_card_compact',
  CYCLE_SIGNAL_BAR: 'cycle_signal_bar',
  CLEAR_WINDOW_BANNER: 'clear_window_banner',
  // Week 3 — Runners
  MANTRA_RUNNER_DISPLAY: 'mantra_runner_display',
  SANKALP_HOLD: 'sankalp_hold',
  PRACTICE_TIMER: 'practice_timer',
  COMPLETION_RETURN: 'completion_return',
  // Week 4 — Support
  TRIGGER_ENTRY: 'trigger_entry',
  SOUND_BRIDGE_TRANSIENT: 'sound_bridge_transient',
  CHECKIN_REGULATION: 'checkin_regulation',
  BALANCED_ACK_OVERLAY: 'balanced_ack_overlay',
  VOICE_NOTE_SHEET: 'voice_note_sheet',
  VOICE_CONSENT_SHEET: 'voice_consent_sheet',
  // Week 5 — Reflection + Checkpoints
  EVENING_REFLECTION: 'evening_reflection',
  WEEKLY_REFLECTION: 'weekly_reflection',
  CHECKPOINT_DAY_7: 'checkpoint_day_7',
  CHECKPOINT_DAY_14: 'checkpoint_day_14',
  CHECKPOINT_DAY_14_FINALE: 'checkpoint_day_14_finale',
  RESILIENCE_NARRATIVE_CARD: 'resilience_narrative_card',
  // Week 6 — Companion Intelligence
  PREP_COACHING_SHEET: 'prep_coaching_sheet',
  ENTITY_RECOGNITION_SHEET: 'entity_recognition_sheet',
  RECOMMENDED_ADDITIONAL_CARD: 'recommended_additional_card',
  POST_CONFLICT_GENTLENESS_CARD: 'post_conflict_gentleness_card',
  // Week 7 — Why-This + Gratitude/Season
  WHY_THIS_L2: 'why_this_l2',
  WHY_THIS_L3: 'why_this_l3',
  GRATITUDE_JOY_CARD: 'gratitude_joy_card',
  SEASON_CHANGE_BANNER: 'season_change_banner',
  COMPANIONED_CHANT: 'companioned_chant',
  // Week 8 — New Dashboard v3
  NEW_DASHBOARD_BODY: 'new_dashboard_body',
  // Support rooms
  GRIEF_ROOM_BODY: 'grief_room_body',
  LONELINESS_ROOM_BODY: 'loneliness_room_body',
  JOY_ROOM_BODY: 'joy_room_body',
  GROWTH_ROOM_BODY: 'growth_room_body',
} as const;

export type BlockType = (typeof BLOCK_TYPES)[keyof typeof BLOCK_TYPES];
