export const TEMPLE_LIST = [
  // NORTH INDIA
  {
    key: "vaishno_devi_temple",
    location: "Katra, Jammu & Kashmir",
    region: "North",
    category: "Devi (D)",
    popularity: "high",
    accessibility: "remote",
    verified: true,
    latitude: 33.0121,
    longitude: 74.9481,
  },
  {
    key: "amarnath_cave_temple",
    location: "Pahalgam, Jammu & Kashmir",
    region: "North",
    category: "Shiva (Sh), Shakti Peetha (S)",
    popularity: "high",
    accessibility: "remote",
    verified: true,
    latitude: 34.2152,
    longitude: 75.4267,
  },
  {
    key: "kheer_bhawani_temple",
    location: "Ganderbal, Jammu & Kashmir",
    region: "North",
    category: "Devi (D)",
    popularity: "medium",
    accessibility: "remote",
    verified: true,
    latitude: 34.2197,
    longitude: 74.7792,
  },
  {
    key: "kedarnath_temple",
    location: "Kedarnath, Uttarakhand",
    region: "North",
    category: "Shiva (Sh), Jyotirlinga (J), Chota Char Dham (CCD)",
    popularity: "high",
    accessibility: "remote",
    verified: true,
    latitude: 30.7353,
    longitude: 79.0669,
  },
  {
    key: "badrinath_temple",
    location: "Badrinath, Uttarakhand",
    region: "North",
    category: "Vishnu (V), Char Dham (CD), Chota Char Dham (CCD)",
    popularity: "high",
    accessibility: "remote",
    verified: true,
    latitude: 30.7447,
    longitude: 79.4887,
  },
  {
    key: "gangotri_temple",
    location: "Gangotri, Uttarakhand",
    region: "North",
    category: "Devi (D), Chota Char Dham (CCD)",
    popularity: "medium",
    accessibility: "remote",
    verified: true,
    latitude: 30.9917,
    longitude: 78.9366,
  },
  {
    key: "yamunotri_temple",
    location: "Yamunotri, Uttarakhand",
    region: "North",
    category: "Devi (D), Chota Char Dham (CCD)",
    popularity: "medium",
    accessibility: "remote",
    verified: true,
    latitude: 31.0165,
    longitude: 78.4566,
  },
  {
    key: "kashi_vishwanath_temple",
    location: "Varanasi, Uttar Pradesh",
    region: "North",
    category: "Shiva (Sh), Jyotirlinga (J), Shakti Peetha (S)",
    popularity: "high",
    accessibility: "urban",
    verified: true,
    latitude: 25.3106,
    longitude: 83.0104,
  },
  {
    key: "ram_janmabhoomi_temple",
    location: "Ayodhya, Uttar Pradesh",
    region: "North",
    category: "Vishnu (V)",
    popularity: "high",
    accessibility: "urban",
    verified: true,
    latitude: 26.7967,
    longitude: 82.1972,
  },
  {
    key: "krishna_janmabhoomi_temple_complex",
    location: "Mathura, Uttar Pradesh",
    region: "North",
    category: "Vishnu (V), Shakti Peetha (S)",
    popularity: "high",
    accessibility: "urban",
    verified: true,
    latitude: 27.4924,
    longitude: 77.6734,
  },
  {
    key: "banke_bihari_temple",
    location: "Vrindavan, Uttar Pradesh",
    region: "North",
    category: "Vishnu (V)",
    popularity: "high",
    accessibility: "urban",
    verified: true,
    latitude: 27.5786,
    longitude: 77.6706,
  },
  {
    key: "prem_mandir",
    location: "Vrindavan, Uttar Pradesh",
    region: "North",
    category: "Vishnu (V)",
    popularity: "medium",
    accessibility: "urban",
    verified: true,
    latitude: 27.5733,
    longitude: 77.6619,
  },
  {
    key: "patal_bhuvaneshwar_cave_temple",
    location: "Pithoragarh, Uttarakhand",
    region: "North",
    category: "Shiva (Sh), Devi (D)",
    popularity: "low",
    accessibility: "remote",
    verified: true,
    latitude: 29.8833,
    longitude: 80.1667,
  },
  {
    key: "mansa_devi_temple",
    location: "Haridwar, Uttarakhand",
    region: "North",
    category: "Devi (D)",
    popularity: "medium",
    accessibility: "urban",
    verified: true,
    latitude: 29.9646,
    longitude: 78.1598,
  },
  {
    key: "chandi_devi_temple",
    location: "Haridwar, Uttarakhand",
    region: "North",
    category: "Devi (D)",
    popularity: "medium",
    accessibility: "urban",
    verified: true,
    latitude: 29.9725,
    longitude: 78.171,
  },
  {
    key: "naina_devi_temple",
    location: "Bilaspur, Himachal Pradesh",
    region: "North",
    category: "Devi (D), Shakti Peetha (S)",
    popularity: "medium",
    accessibility: "remote",
    verified: true,
    latitude: 31.453,
    longitude: 76.5485,
  },
  {
    key: "jwalamukhi_temple",
    location: "Kangra, Himachal Pradesh",
    region: "North",
    category: "Devi (D), Shakti Peetha (S)",
    popularity: "medium",
    accessibility: "remote",
    verified: true,
    latitude: 31.8836,
    longitude: 76.3232,
  },
  {
    key: "chintpurni_temple",
    location: "Una, Himachal Pradesh",
    region: "North",
    category: "Devi (D), Shakti Peetha (S)",
    popularity: "medium",
    accessibility: "remote",
    verified: true,
    latitude: 31.8145,
    longitude: 76.0774,
  },
  {
    key: "baijnath_temple",
    location: "Baijnath, Himachal Pradesh",
    region: "North",
    category: "Shiva (Sh)",
    popularity: "low",
    accessibility: "remote",
    verified: true,
    latitude: 32.053,
    longitude: 76.653,
  },
  {
    key: "chamunda_devi_temple",
    location: "Dharamshala, Himachal Pradesh",
    region: "North",
    category: "Devi (D)",
    popularity: "medium",
    accessibility: "remote",
    verified: true,
    latitude: 32.0589,
    longitude: 76.3204,
  },
  {
    key: "tungnath_temple",
    location: "Rudranath, Uttarakhand",
    region: "North",
    category: "Shiva (Sh)",
    popularity: "low",
    accessibility: "remote",
    verified: true,
    latitude: 30.624,
    longitude: 79.259,
  },
  {
    key: "kalimath_temple",
    location: "Rudraprayag, Uttarakhand",
    region: "North",
    category: "Devi (D)",
    popularity: "low",
    accessibility: "remote",
    verified: true,
    latitude: 30.479,
    longitude: 79.066,
  },
  {
    key: "kurukshetra_shakti_peetha_savitri_temple",
    location: "Kurukshetra, Haryana",
    region: "North",
    category: "Devi (D), Shakti Peetha (S)",
    popularity: "medium",
    accessibility: "urban",
    verified: true,
    latitude: 29.9693,
    longitude: 76.8206,
  },
  {
    key: "patna_devi_temple",
    location: "Patna, Bihar",
    region: "North",
    category: "Devi (D), Shakti Peetha (S)",
    popularity: "medium",
    accessibility: "urban",
    verified: true,
    latitude: 25.5941,
    longitude: 85.1376,
  },
  {
    key: "mangla_gauri_temple",
    location: "Gaya, Bihar",
    region: "North",
    category: "Devi (D), Shakti Peetha (S)",
    popularity: "medium",
    accessibility: "urban",
    verified: true,
    latitude: 24.7475,
    longitude: 84.9982,
  },
  {
    key: "akshardham_temple",
    location: "Delhi",
    region: "North",
    category: "Saint/Sampradaya/Other (Sa), Vishnu (V)",
    popularity: "high",
    accessibility: "urban",
    verified: true,
    latitude: 28.6126,
    longitude: 77.2775,
  },
  {
    key: "birla_mandir_lakshmi_narayan_temple",
    location: "Delhi",
    region: "North",
    category: "Vishnu (V)",
    popularity: "medium",
    accessibility: "urban",
    verified: true,
    latitude: 28.6293,
    longitude: 77.216,
  },
  {
    key: "hemkund_sahib",
    location: "Chamoli, Uttarakhand",
    region: "North",
    category: "Sikh (Sa)",
    popularity: "medium",
    accessibility: "remote",
    verified: true,
    latitude: 30.678,
    longitude: 79.61,
  },
  {
    key: "rudranath_temple",
    location: "Chamoli, Uttarakhand",
    region: "North",
    category: "Shiva (Sh)",
    popularity: "low",
    accessibility: "remote",
    verified: true,
    latitude: 30.529,
    longitude: 79.318,
  },
  // WEST INDIA
  {
    key: "somnath_temple",
    location: "Veraval, Gujarat",
    region: "West",
    category: "Shiva (Sh), Jyotirlinga (J)",
    popularity: "high",
    accessibility: "remote",
    verified: true,
    latitude: 20.888,
    longitude: 70.401,
  },
  {
    key: "dwarkadhish_temple",
    location: "Dwarka, Gujarat",
    region: "West",
    category: "Vishnu (V), Char Dham (CD)",
    popularity: "high",
    accessibility: "urban",
    verified: true,
    latitude: 22.2412,
    longitude: 68.9677,
  },
  {
    key: "nageshwar_jyotirlinga",
    location: "Dwarka, Gujarat",
    region: "West",
    category: "Shiva (Sh), Jyotirlinga (J)",
    popularity: "medium",
    accessibility: "remote",
    verified: true,
    latitude: 22.2525,
    longitude: 68.9875,
  },
  {
    key: "ambaji_temple",
    location: "Ambaji, Gujarat",
    region: "West",
    category: "Devi (D), Shakti Peetha (S)",
    popularity: "medium",
    accessibility: "remote",
    verified: true,
    latitude: 24.3272,
    longitude: 72.8543,
  },
  {
    key: "mahakali_temple",
    location: "Pavagadh, Gujarat",
    region: "West",
    category: "Devi (D), Shakti Peetha (S)",
    popularity: "medium",
    accessibility: "remote",
    verified: true,
    latitude: 22.45,
    longitude: 73.5167,
  },
  {
    key: "trimbakeshwar_shiva_temple",
    location: "Nashik, Maharashtra",
    region: "West",
    category: "Shiva (Sh), Jyotirlinga (J), Shakti Peetha (S)",
    popularity: "high",
    accessibility: "remote",
    verified: true,
    latitude: 19.93,
    longitude: 73.53,
  },
  {
    key: "bhimashankar_temple",
    location: "Pune, Maharashtra",
    region: "West",
    category: "Shiva (Sh), Jyotirlinga (J)",
    popularity: "medium",
    accessibility: "remote",
    verified: true,
    latitude: 19.0686,
    longitude: 73.558,
  },
  {
    key: "grishneshwar_jyotirlinga_temple",
    location: "Ellora, Maharashtra",
    region: "West",
    category: "Shiva (Sh), Jyotirlinga (J)",
    popularity: "medium",
    accessibility: "remote",
    verified: true,
    latitude: 20.0185,
    longitude: 75.1762,
  },
  {
    key: "mahalaxmi_temple",
    location: "Kolhapur, Maharashtra",
    region: "West",
    category: "Devi (D), Shakti Peetha (S)",
    popularity: "high",
    accessibility: "urban",
    verified: true,
    latitude: 16.695,
    longitude: 74.2333,
  },
  {
    key: "siddhivinayak_temple",
    location: "Mumbai, Maharashtra",
    region: "West",
    category: "Ganesha",
    popularity: "high",
    accessibility: "urban",
    verified: true,
    latitude: 19.015,
    longitude: 72.8333,
  },
  {
    key: "renuka_devi_temple",
    location: "Mahur, Maharashtra",
    region: "West",
    category: "Devi (D), Shakti Peetha (S)",
    popularity: "medium",
    accessibility: "remote",
    verified: true,
    latitude: 19.848,
    longitude: 77.918,
  },
  {
    key: "tulja_bhavani_temple",
    location: "Tuljapur, Maharashtra",
    region: "West",
    category: "Devi (D)",
    popularity: "medium",
    accessibility: "remote",
    verified: true,
    latitude: 17.999,
    longitude: 76.131,
  },
  {
    key: "shirdi_sai_baba_temple",
    location: "Shirdi, Maharashtra",
    region: "West",
    category: "Saint/Sampradaya/Other (Sa)",
    popularity: "high",
    accessibility: "urban",
    verified: true,
    latitude: 19.766,
    longitude: 74.477,
  },
  {
    key: "ganpatipule_temple",
    location: "Ganpatipule, Maharashtra",
    region: "West",
    category: "Ganesha",
    popularity: "medium",
    accessibility: "remote",
    verified: true,
    latitude: 17.083,
    longitude: 73.25,
  },
  {
    key: "pushkar_brahma_temple",
    location: "Pushkar, Rajasthan",
    region: "West",
    category: "Brahma",
    popularity: "medium",
    accessibility: "urban",
    verified: true,
    latitude: 26.49,
    longitude: 74.55,
  },
  {
    key: "karni_mata_temple",
    location: "Deshnok, Rajasthan",
    region: "West",
    category: "Devi (D)",
    popularity: "medium",
    accessibility: "remote",
    verified: true,
    latitude: 27.794,
    longitude: 73.343,
  },
  {
    key: "nathdwara_shrinathji_temple",
    location: "Nathdwara, Rajasthan",
    region: "West",
    category: "Vishnu (V)",
    popularity: "high",
    accessibility: "urban",
    verified: true,
    latitude: 24.935,
    longitude: 73.824,
  },
  {
    key: "dilwara_temples",
    location: "Mount Abu, Rajasthan",
    region: "West",
    category: "Jain",
    popularity: "medium",
    accessibility: "remote",
    verified: true,
    latitude: 24.618,
    longitude: 72.708,
  },
  {
    key: "shani_shingnapur",
    location: "Shingnapur, Maharashtra",
    region: "West",
    category: "Shani (Sa)",
    popularity: "high",
    accessibility: "remote",
    verified: true,
    latitude: 19.769,
    longitude: 74.626,
  },
  {
    key: "ambika_mata_temple",
    location: "Girnar, Gujarat",
    region: "West",
    category: "Devi (D)",
    popularity: "medium",
    accessibility: "remote",
    verified: true,
    latitude: 21.489,
    longitude: 70.505,
  },
  {
    key: "ranakpur_jain_temple",
    location: "Ranakpur, Rajasthan",
    region: "West",
    category: "Jain",
    popularity: "medium",
    accessibility: "remote",
    verified: true,
    latitude: 25.1167,
    longitude: 73.4667,
  },
  // CENTRAL INDIA
  {
    key: "mahakaleshwar_jyotirlinga_temple",
    location: "Ujjain, Madhya Pradesh",
    region: "Central",
    category: "Shiva (Sh), Jyotirlinga (J), Shakti Peetha (S)",
    popularity: "high",
    accessibility: "urban",
    verified: true,
    latitude: 23.177,
    longitude: 75.786,
  },
  {
    key: "omkareshwar_jyotirlinga_temple",
    location: "Khandwa, Madhya Pradesh",
    region: "Central",
    category: "Shiva (Sh), Jyotirlinga (J)",
    popularity: "medium",
    accessibility: "remote",
    verified: true,
    latitude: 22.245,
    longitude: 76.15,
  },
  {
    key: "harsiddhi_temple",
    location: "Ujjain, Madhya Pradesh",
    region: "Central",
    category: "Devi (D), Shakti Peetha (S)",
    popularity: "medium",
    accessibility: "urban",
    verified: true,
    latitude: 23.178,
    longitude: 75.787,
  },
  {
    key: "kalmadhav_shonbhadra_shakti_peetha",
    location: "Amarkantak, Madhya Pradesh",
    region: "Central",
    category: "Devi (D), Shakti Peetha (S)",
    popularity: "low",
    accessibility: "remote",
    verified: true,
    latitude: 22.672,
    longitude: 81.76,
  },
  {
    key: "khajuraho_group_of_temples",
    location: "Khajuraho, Madhya Pradesh",
    region: "Central",
    category: "Vishnu (V), Shiva (Sh)",
    popularity: "high",
    accessibility: "remote",
    verified: true,
    latitude: 24.831,
    longitude: 79.92,
  },
  {
    key: "chitrakoot_shakti_peetha_ramgiri",
    location: "Satna, Madhya Pradesh",
    region: "Central",
    category: "Devi (D), Shakti Peetha (S)",
    popularity: "medium",
    accessibility: "remote",
    verified: true,
    latitude: 25.151,
    longitude: 81.102,
  },
  {
    key: "danteshwari_temple",
    location: "Dantewada, Chhattisgarh",
    region: "Central",
    category: "Devi (D), Shakti Peetha (S)",
    popularity: "medium",
    accessibility: "remote",
    verified: true,
    latitude: 18.892,
    longitude: 81.357,
  },
  {
    key: "bambleshwari_temple",
    location: "Dongargarh, Chhattisgarh",
    region: "Central",
    category: "Devi (D)",
    popularity: "medium",
    accessibility: "remote",
    verified: true,
    latitude: 21.183,
    longitude: 80.767,
  },
  {
    key: "tulsi_manas_temple",
    location: "Chitrakoot, Madhya Pradesh",
    region: "Central",
    category: "Vishnu (V)",
    popularity: "medium",
    accessibility: "remote",
    verified: true,
    latitude: 25.159,
    longitude: 81.106,
  },
  // EAST INDIA
  {
    key: "jagannath_temple",
    location: "Puri, Odisha",
    region: "East",
    category: "Vishnu (V), Char Dham (CD), Shakti Peetha (S)",
    popularity: "high",
    accessibility: "urban",
    verified: true,
    latitude: 19.81,
    longitude: 85.82,
  },
  {
    key: "konark_sun_temple",
    location: "Konark, Odisha",
    region: "East",
    category: "Surya Dev",
    popularity: "high",
    accessibility: "remote",
    verified: true,
    latitude: 19.885,
    longitude: 86.09,
  },
  {
    key: "lingaraj_temple",
    location: "Bhubaneswar, Odisha",
    region: "East",
    category: "Shiva (Sh), Vishnu (V)",
    popularity: "high",
    accessibility: "urban",
    verified: true,
    latitude: 20.238,
    longitude: 85.838,
  },
  {
    key: "kamakhya_temple",
    location: "Guwahati, Assam",
    region: "East",
    category: "Devi (D), Shakti Peetha (S)",
    popularity: "high",
    accessibility: "urban",
    verified: true,
    latitude: 26.173,
    longitude: 91.698,
  },
  {
    key: "kalighat_kali_temple",
    location: "Kolkata, West Bengal",
    region: "East",
    category: "Devi (D), Shakti Peetha (S)",
    popularity: "high",
    accessibility: "urban",
    verified: true,
    latitude: 22.514,
    longitude: 88.34,
  },
  {
    key: "dakshineswar_kali_temple",
    location: "Kolkata, West Bengal",
    region: "East",
    category: "Devi (D)",
    popularity: "high",
    accessibility: "urban",
    verified: true,
    latitude: 22.657,
    longitude: 88.357,
  },
  {
    key: "tara_tarini_temple",
    location: "Ganjam, Odisha",
    region: "East",
    category: "Devi (D), Shakti Peetha (S)",
    popularity: "medium",
    accessibility: "remote",
    verified: true,
    latitude: 19.676,
    longitude: 84.908,
  },
  {
    key: "baidyanath_dham",
    location: "Deoghar, Jharkhand",
    region: "East",
    category: "Shiva (Sh), Jyotirlinga (J), Shakti Peetha (S)",
    popularity: "high",
    accessibility: "urban",
    verified: true,
    latitude: 24.489,
    longitude: 86.414,
  },
  {
    key: "iskcon_temple",
    location: "Mayapur, West Bengal",
    region: "East",
    category: "Vishnu (V), Saint/Sampradaya/Other (Sa)",
    popularity: "medium",
    accessibility: "remote",
    verified: true,
    latitude: 23.428,
    longitude: 88.394,
  },
  {
    key: "bakreshwar_temple",
    location: "Birbhum, West Bengal",
    region: "East",
    category: "Shiva (Sh), Shakti Peetha (S)",
    popularity: "low",
    accessibility: "remote",
    verified: true,
    latitude: 23.88,
    longitude: 87.37,
  },
  {
    key: "tarapith_temple",
    location: "Birbhum, West Bengal",
    region: "East",
    category: "Devi (D)",
    popularity: "medium",
    accessibility: "remote",
    verified: true,
    latitude: 24.112,
    longitude: 87.8,
  },
  {
    key: "phullara_temple",
    location: "Birbhum, West Bengal",
    region: "East",
    category: "Devi (D), Shakti Peetha (S)",
    popularity: "low",
    accessibility: "remote",
    verified: true,
    latitude: 23.5,
    longitude: 87.85,
  },
  {
    key: "bahula_shakti_peetha",
    location: "Ketugram, West Bengal",
    region: "East",
    category: "Devi (D), Shakti Peetha (S)",
    popularity: "low",
    accessibility: "remote",
    verified: true,
    latitude: 23.583,
    longitude: 88.083,
  },
  {
    key: "ujaani_shakti_peetha",
    location: "Burdwan, West Bengal",
    region: "East",
    category: "Devi (D), Shakti Peetha (S)",
    popularity: "low",
    accessibility: "remote",
    verified: true,
    latitude: 23.233,
    longitude: 87.85,
  },
  {
    key: "kiriteswari_temple",
    location: "Murshidabad, West Bengal",
    region: "East",
    category: "Devi (D), Shakti Peetha (S)",
    popularity: "low",
    accessibility: "remote",
    verified: true,
    latitude: 24.183,
    longitude: 88.267,
  },
  {
    key: "jayanti_shakti_peetha",
    location: "Jaintia Hills, Meghalaya",
    region: "East",
    category: "Devi (D), Shakti Peetha (S)",
    popularity: "low",
    accessibility: "remote",
    verified: true,
    latitude: 25.467,
    longitude: 92.267,
  },
  {
    key: "tripura_sundari_temple",
    location: "Udaipur, Tripura",
    region: "East",
    category: "Devi (D), Shakti Peetha (S)",
    popularity: "medium",
    accessibility: "urban",
    verified: true,
    latitude: 23.533,
    longitude: 91.283,
  },
  {
    key: "belur_math",
    location: "Howrah, West Bengal",
    region: "East",
    category: "Saint/Sampradaya/Other (Sa)",
    popularity: "medium",
    accessibility: "urban",
    verified: true,
    latitude: 22.629,
    longitude: 88.364,
  },
  // SOUTH INDIA
  {
    key: "sri_venkateswara_swamy_temple",
    location: "Tirupati, Andhra Pradesh",
    region: "South",
    category: "Vishnu (V)",
    popularity: "high",
    accessibility: "urban",
    verified: true,
    latitude: 13.683,
    longitude: 79.347,
  },
  {
    key: "mallikarjuna_swamy_temple",
    location: "Srisailam, Andhra Pradesh",
    region: "South",
    category: "Shiva (Sh), Jyotirlinga (J), Shakti Peetha (S)",
    popularity: "high",
    accessibility: "remote",
    verified: true,
    latitude: 16.075,
    longitude: 78.87,
  },
  {
    key: "kanaka_durga_temple",
    location: "Vijayawada, Andhra Pradesh",
    region: "South",
    category: "Devi (D), Shakti Peetha (S)",
    popularity: "high",
    accessibility: "urban",
    verified: true,
    latitude: 16.5,
    longitude: 80.65,
  },
  {
    key: "srikalahasteeswara_temple",
    location: "Srikalahasti, Andhra Pradesh",
    region: "South",
    category: "Shiva (Sh)",
    popularity: "medium",
    accessibility: "urban",
    verified: true,
    latitude: 13.75,
    longitude: 79.7,
  },
  {
    key: "jogulamba_temple",
    location: "Alampur, Telangana",
    region: "South",
    category: "Devi (D), Shakti Peetha (S)",
    popularity: "medium",
    accessibility: "remote",
    verified: true,
    latitude: 15.88,
    longitude: 78.13,
  },
  {
    key: "ramanathaswamy_temple",
    location: "Rameswaram, Tamil Nadu",
    region: "South",
    category: "Shiva (Sh), Jyotirlinga (J), Char Dham (CD)",
    popularity: "high",
    accessibility: "urban",
    verified: true,
    latitude: 9.287,
    longitude: 79.312,
  },
  {
    key: "meenakshi_amman_temple",
    location: "Madurai, Tamil Nadu",
    region: "South",
    category: "Devi (D), Shiva (Sh)",
    popularity: "high",
    accessibility: "urban",
    verified: true,
    latitude: 9.919,
    longitude: 78.119,
  },
  {
    key: "sree_padmanabhaswamy_temple",
    location: "Thiruvananthapuram, Kerala",
    region: "South",
    category: "Vishnu (V)",
    popularity: "high",
    accessibility: "urban",
    verified: true,
    latitude: 8.948,
    longitude: 76.586,
  },
  {
    key: "guruvayur_sree_krishna_temple",
    location: "Guruvayoor, Kerala",
    region: "South",
    category: "Vishnu (V)",
    popularity: "high",
    accessibility: "urban",
    verified: true,
    latitude: 10.595,
    longitude: 76.04,
  },
  {
    key: "sabarimala_ayyappan_temple",
    location: "Pathanamthitta, Kerala",
    region: "South",
    category: "Ayyappan",
    popularity: "high",
    accessibility: "remote",
    verified: true,
    latitude: 9.435,
    longitude: 77.085,
  },
  {
    key: "kamakshi_amman_temple",
    location: "Kanchipuram, Tamil Nadu",
    region: "South",
    category: "Devi (D), Shakti Peetha (S)",
    popularity: "high",
    accessibility: "urban",
    verified: true,
    latitude: 12.837,
    longitude: 79.706,
  },
  {
    key: "varadaraja_perumal_temple",
    location: "Kanchipuram, Tamil Nadu",
    region: "South",
    category: "Vishnu (V)",
    popularity: "medium",
    accessibility: "urban",
    verified: true,
    latitude: 12.831,
    longitude: 79.702,
  },
  {
    key: "ekambareswarar_temple",
    location: "Kanchipuram, Tamil Nadu",
    region: "South",
    category: "Shiva (Sh)",
    popularity: "medium",
    accessibility: "urban",
    verified: true,
    latitude: 12.857,
    longitude: 79.694,
  },
  {
    key: "brihadeeswarar_temple",
    location: "Thanjavur, Tamil Nadu",
    region: "South",
    category: "Shiva (Sh)",
    popularity: "high",
    accessibility: "urban",
    verified: true,
    latitude: 10.783,
    longitude: 79.132,
  },
  {
    key: "ranganathaswamy_temple",
    location: "Srirangam, Tamil Nadu",
    region: "South",
    category: "Vishnu (V)",
    popularity: "high",
    accessibility: "urban",
    verified: true,
    latitude: 10.862,
    longitude: 78.694,
  },
  {
    key: "palani_murugan_temple",
    location: "Palani, Tamil Nadu",
    region: "South",
    category: "Murugan",
    popularity: "high",
    accessibility: "urban",
    verified: true,
    latitude: 10.448,
    longitude: 77.52,
  },
  {
    key: "udupi_sri_krishna_matha",
    location: "Udupi, Karnataka",
    region: "South",
    category: "Vishnu (V)",
    popularity: "high",
    accessibility: "urban",
    verified: true,
    latitude: 13.338,
    longitude: 74.747,
  },
  {
    key: "chamundeshwari_temple",
    location: "Mysore, Karnataka",
    region: "South",
    category: "Devi (D), Shakti Peetha (S)",
    popularity: "medium",
    accessibility: "urban",
    verified: true,
    latitude: 12.295,
    longitude: 76.665,
  },
  {
    key: "mookambika_temple",
    location: "Kollur, Karnataka",
    region: "South",
    category: "Devi (D)",
    popularity: "medium",
    accessibility: "remote",
    verified: true,
    latitude: 13.86,
    longitude: 74.82,
  },
  {
    key: "virupaksha_temple",
    location: "Hampi, Karnataka",
    region: "South",
    category: "Shiva (Sh)",
    popularity: "high",
    accessibility: "remote",
    verified: true,
    latitude: 15.335,
    longitude: 76.46,
  },
  {
    key: "mahabaleshwar_temple",
    location: "Gokarna, Karnataka",
    region: "South",
    category: "Shiva (Sh)",
    popularity: "medium",
    accessibility: "remote",
    verified: true,
    latitude: 14.55,
    longitude: 74.32,
  },
  {
    key: "kotilingeshwara_temple",
    location: "Kolar, Karnataka",
    region: "South",
    category: "Shiva (Sh)",
    popularity: "medium",
    accessibility: "remote",
    verified: true,
    latitude: 13.13,
    longitude: 78.13,
  },
  {
    key: "chennakesava_temple",
    location: "Belur, Karnataka",
    region: "South",
    category: "Vishnu (V)",
    popularity: "medium",
    accessibility: "remote",
    verified: true,
    latitude: 13.16,
    longitude: 75.86,
  },
  {
    key: "suchindram_thanumalayan_temple",
    location: "Suchindram, Tamil Nadu",
    region: "South",
    category: "Shiva (Sh), Vishnu (V), Brahma",
    popularity: "medium",
    accessibility: "urban",
    verified: true,
    latitude: 8.127,
    longitude: 77.468,
  },
  {
    key: "kumari_amman_temple",
    location: "Kanyakumari, Tamil Nadu",
    region: "South",
    category: "Devi (D), Shakti Peetha (S)",
    popularity: "medium",
    accessibility: "urban",
    verified: true,
    latitude: 8.087,
    longitude: 77.538,
  },
  {
    key: "attukal_bhagavathy_temple",
    location: "Thiruvananthapuram, Kerala",
    region: "South",
    category: "Devi (D)",
    popularity: "high",
    accessibility: "urban",
    verified: true,
    latitude: 8.5,
    longitude: 76.95,
  },
  {
    key: "vadakkumnathan_temple",
    location: "Thrissur, Kerala",
    region: "South",
    category: "Shiva (Sh)",
    popularity: "medium",
    accessibility: "urban",
    verified: true,
    latitude: 10.526,
    longitude: 76.214,
  },
  {
    key: "azhagar_kovil",
    location: "Madurai, Tamil Nadu",
    region: "South",
    category: "Vishnu (V)",
    popularity: "medium",
    accessibility: "urban",
    verified: true,
    latitude: 10.063,
    longitude: 78.229,
  },
  {
    key: "guruvayurappan_temple",
    location: "Thrissur, Kerala",
    region: "South",
    category: "Vishnu (V)",
    popularity: "high",
    accessibility: "urban",
    verified: true,
    latitude: 10.594,
    longitude: 76.042,
  },
  {
    key: "parthasarathy_temple",
    location: "Triplicane, Tamil Nadu",
    region: "South",
    category: "Vishnu (V)",
    popularity: "medium",
    accessibility: "urban",
    verified: true,
    latitude: 13.061,
    longitude: 80.274,
  },
];

export const RITUALS = {
  "Devi (D)": [
    "lalita_pooja",
    "durga_pooja",
    "navratri_havan",
    "chandi_homa",
    "kumari_puja",
  ],
  "Vishnu (V)": [
    "lakshmi_pooja",
    "satyanarayan_katha",
    "vishnu_sahasranama",
    "annakut",
    "govinda_patra",
  ],
  "Shiva (Sh)": [
    "rudrabhishek",
    "maha_mrityunjaya_jaap",
    "shiva_lingam_abhishek",
    "panchamrit_abhishek",
    "kailash_yatra_pooja",
  ],
  "Jyotirlinga (J)": [
    "rudrabhishek",
    "maha_shivaratri_pooja",
    "jyotirlinga_abhishek",
    "somnath_mahapuja",
    "kedarnath_shivling_puja",
  ],
  "Shakti Peetha (S)": [
    "chandi_path",
    "devi_mahatmyam",
    "kumari_pooja",
    "kamakhya_tantra_puja",
    "vaishno_devi_aarti",
  ],
  "Char Dham (CD)": [
    "gangajal_abhishek",
    "yamuna_aarti",
    "char_dham_yatra_pooja",
    "rameswaram_sethu_snan",
  ],
  "Chota Char Dham (CCD)": [
    "gangotri_ganga_pooja",
    "yamunotri_aarti",
    "kedarnath_shiva_pooja",
    "badrinath_vishnu_puja",
  ],
  "Saint/Sampradaya/Other (Sa)": [
    "sai_baba_aarti",
    "guru_purnima_pooja",
    "sampradaya_havan",
    "shirdi_sai_satyanarayan_puja",
  ],
  Ganesha: [
    "ganesh_atharvashirsha",
    "modak_pooja",
    "vinayaka_chaturthi_havan",
    "siddhivinayak_abhishek",
  ],
  Brahma: [
    "brahma_gayatri_mantra",
    "sarva_devata_pooja",
    "pushkar_brahma_yagna",
  ],
  "Surya Dev": [
    "surya_namaskar_pooja",
    "arghya_to_surya",
    "konark_surya_aradhana",
  ],
  Ayyappan: [
    "sabarimala_ayyappa_pooja",
    "swami_saranam_bhajan",
    "makara_jyoti_darshan",
  ],
  Murugan: ["kanda_shasti_kavacham", "vel_pooja", "thaipusam_kavadi"],
  "Shani (Sa)": [
    "shani_shanti_pooja",
    "shani_trayodashi_havan",
    "shani_shingnapur_oil_abhishek",
  ],
  Jain: ["jain_namokar_mantra", "panch_kalyanak_puja", "dilwara_mahavir_puja"],
};
